version = 0.1

[default.deploy.parameters]
stack_name = "math-is-punk-backend"
resolve_s3 = true
s3_prefix = "math-is-punk-backend"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
